# Generated by Django 4.1 on 2022-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('fecha', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('situacion', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSuscripcion', models.CharField(max_length=40)),
                ('apellidoSuscripcion', models.CharField(max_length=40)),
                ('emailSuscripcion', models.EmailField(max_length=254)),
            ],
        ),
    ]
