# Generated by Django 4.1 on 2022-09-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='dniSuscripciones1',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
